name: FreshMe
favicon: null
layout_spectrum: 0.24836
typography_spectrum: 0.74745
title: от Арон
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e30614'
    - '#f8b000'
    - '#e84e1c'
    - '#94c11e'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
