name: FreshMe
favicon: null
layout_spectrum: 0.48754
typography_spectrum: 0.75317
title: FreshMe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7e00'
    - '#ff0000'
    - '#7eff00'
    - '#ff3200'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
