name: FreshMe
favicon: null
layout_spectrum: 0.49924174253828824
typography_spectrum: 0.7987359100952744
title: FreshMe от Арон
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.17376505280844867
  lightness: 0.18991408846341074
  saturation: 0.29012977541424334
  rhythmicContrast: 0.33086245344020426
purpose: []
