name: FreshMe
favicon: null
layout_spectrum: 0.2541
typography_spectrum: 0.75647
title: FreshMe от Арон
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7e00'
    - '#ff0000'
    - '#7eff00'
    - '#ff3200'
  brandStrength: 0
  lightness: 0.18991408846341074
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
