name: FreshMe от Арон
favicon: null
layout_spectrum: 0.23603
typography_spectrum: 0.5107
title: FreshMe
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f18d39'
    - '#f9d1a8'
    - '#8eba44'
    - '#e33434'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
