name: FreshMe
favicon: null
layout_spectrum: 0.24356
typography_spectrum: 0.75392
title: от Арон
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7e00'
    - '#ff0000'
    - '#7eff00'
    - '#ff3200'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
