name: FreshMe
favicon: null
layout_spectrum: 0.36676
typography_spectrum: 0.25157
title: FreshMe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f18d39'
    - '#f9d1a8'
    - '#8eba44'
    - '#e33434'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
